refactor(ci): handle tag as a step output
This makes it simpler, while remaining safe, to add further steps
to the 'publish' job. Also, it is more semantically relevant to
generate and pass around the tag string, rather than passing just
the version and prefixing the 'v' on every place the tag is needed.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -111,28 +111,31 @@ jobs:
       with:
         python-version: ${{ env.PYTHON_VERSION }}
     - name: Extract version
+      id: tag
       run: |
-            package_version=$(awk -F' = ' '/^version/ {print $2}' wedge-cli/setup.cfg | tr -d "'")
-            echo "PACKAGE_VERSION=$package_version" >> "$GITHUB_ENV"
+        package_version=$(awk -F' = ' '/^version/ {print $2}' wedge-cli/setup.cfg | tr -d "'")
+        echo "string=v$package_version" >> "$GITHUB_OUTPUT"
     - name: Check
       uses: mukunku/tag-exists-action@v1.6.0
       id: check-tag
       with:
-        tag: v${{ env.PACKAGE_VERSION }}
+        tag: ${{ steps.tag.outputs.string }}
+    - name: Fail if tag already exists
+      if: steps.check-tag.outputs.exists != 'false'
+      run: |
+        echo "::error file=ci.yaml::Tag ${{ steps.tag.outputs.string }} already exists!"
+        exit 1
     - name: Tag new version
       uses: tvdias/github-tagger@v0.0.2
-      if: steps.check-tag.outputs.exists == 'false'
       with:
         repo-token: ${{ secrets.TOKEN_PACKAGES }}
-        tag: v${{ env.PACKAGE_VERSION }}
+        tag: ${{ steps.tag.outputs.string }}
     - name: Build wheel
-      if: steps.check-tag.outputs.exists == 'false'
       run: |
         python3 -m pip install build
         python3 -m build wedge-cli/ --wheel
     - name: Upload to AZ
       uses: bacongobbler/azure-blob-storage-upload@main
-      if: steps.check-tag.outputs.exists == 'false'
       with:
         source_dir: wedge-cli/dist
         container_name: main
